#!/usr/bin/env python3
"""
An autogenerated testfile for python.
"""

import unittest
import os
import random
import sys
from io import StringIO
from unittest.mock import patch
from unittest import TextTestRunner
from examiner import ExamTestCase, ExamTestResult, tags
from examiner import import_module, find_path_to_assignment


FILE_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_PATH = find_path_to_assignment(FILE_DIR)

if REPO_PATH not in sys.path:
    sys.path.insert(0, REPO_PATH)

# Path to file and basename of the file to import
die = import_module(REPO_PATH, 'src/die')



class Test1Die(ExamTestCase):
    def setUp(self):
        random.seed("yahtzee")


    @tags("die")
    def test_create_with_random_value(self):
        """
        Testar DESCRIPTION
        Förväntar att ett värde har slumpats till attributet _value:
        {correct}
        Innehöll följande:
        {student}
        """
        d1 = die.Die()
        self.assertEqual(d1._value, 2)



if __name__ == '__main__':
    runner = TextTestRunner(resultclass=ExamTestResult, verbosity=2)
    unittest.main(testRunner=runner, exit=False)
