language: python

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"
    - "nightly"

sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- pylint
            #- php-codesniffer
            #- phpmd
            #- shellcheck



matrix:
    allow_failures:
        - python: "3.7-dev"
        - python: "nightly"



before_script:
    - make python-venv
    - . .venv/bin/activate
    - make python-install install
    #- make install



script:
    - make test



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/d9c52b8ba1381b30286f

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
