version: "3"

# volumes:
#     mysql_data: {}
#     mariadb_data: {}

services:
    # Primary services to use with this course
    oopython: &oopython
        image: dbwebb/courserepo:oopython
        volumes:
            - ".:/home/dbwebb/repo"
            - "/home/dbwebb/repo/bin"
            - "/home/dbwebb/repo/build"
            - "/home/dbwebb/repo/node_modules"
            - "/home/dbwebb/repo/vendor"
            #- "./example/sql/inspect/my.cnf:/home/dbwebb/.my.cnf"

    cli:
        <<: *oopython

    server:
        <<: *oopython
        ports:
            - "18080:80"

    courserepo:
        image: dbwebb/courserepo:cli
        volumes:
            - ".:/home/dbwebb/repo"
            #- "/home/dbwebb/repo/bin"
            #- "/home/dbwebb/repo/build"
            #- "/home/dbwebb/repo/node_modules"
            #- "/home/dbwebb/repo/vendor"
            #- "./example/sql/inspect/my.cnf:/home/dbwebb/.my.cnf"