# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - run: sudo apt-get install -y nodejs npm && sudo ln /usr/local/bin/nodejs /usr/local/bin/node

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum ".requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            #python3 -m venv venv
            #. venv/bin/activate
            #pip install -r requirements.txt
            make python-venv
            . .venv/bin/activate
            make python-install install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum ".requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            #. venv/bin/activate
            #python manage.py test
            . .venv/bin/activate
            make test

      - store_artifacts:
          path: test-reports
          destination: test-reports

notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: https://webhooks.gitter.im/e/4d538d49c841f4f172d6
